version: "2"

plugins:
  eslint:
    enabled: false
    channel: eslint-4
    checks:
      import/no-unresolved:
        enabled: false
  stylelint:
    enabled: true
  structure:
    enabled: false
  duplication:
    enabled: false

exclude_paths:
- .tmp_rules/**/*
- node_modules/**/*

